name: Build

on:
  push:
    branches: ["ci-test"]
  pull_request:
    branches: ["ci-test"]

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Flutter action
        # You may pin to the exact commit or the version.
        # uses: subosito/flutter-action@6c2e035f2692eeac890d854df95630c72673f130
        uses: subosito/flutter-action@v2.6.1
        #with:
        # The Flutter version to make available on the path
        #flutter-version: # optional, default is any
        # The Flutter build release channel
        #channel: # optional, default is stable

      - name: Preprocess
        run: |
          rm lib/config/config.dart
          mv lib/config/config.dart.sample lib/config/config.dart
      - name: Prepare
        run: |
          cd scripts/
          export scripts_path=`pwd`
          export release_bundle_identifier='cn.honjow.fehv'
          export dev_bundle_identifier='dev2.cn.honjow.fehv'
          export pub_output_path="$HOME/Public/fehv";
          export macos_archiver_path="${scripts_path}/../build/macos/Build/Products/Release/fehviewer.app";
          export ios_archiver_path="${scripts_path}/../build/ios/archive/fehviewer.xcarchive/Products/Applications/FEhViewer.app"
          export ipa_plist_path="${ios_archiver_path}/Info.plist"
          export version=`perl version.pl`

          cd ../ios/
          flutter clean
          flutter pub get
          pod update
          pod install
      - name: Build
        run: |
          flutter build ipa --release
          sh ${scripts_path}/reid.sh
          sh ${scripts_path}/zip.sh $version
          sh ${scripts_path}/dsym.sh
      # - name: Upload a Build Artifact
      #   uses: actions/upload-artifact@v3.1.0
      #   with:
      #     # Artifact name
      #     name: # optional, default is artifact
      #     # A file, directory or wildcard pattern that describes what to upload
      #     path:
