name: Build

on:
  push:
    branches: ["ci-test"]
  pull_request:
    branches: ["ci-test"]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3.4.1
        with:
          # The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in README file
          java-version: "18.x"
          # Java distribution. See the list of supported distributions in README file
          distribution: temurin
          cache: gradle # optional

      - name: Flutter action
        # You may pin to the exact commit or the version.
        # uses: subosito/flutter-action@6c2e035f2692eeac890d854df95630c72673f130
        uses: subosito/flutter-action@v2.6.1
        #with:
        # The Flutter version to make available on the path
        #flutter-version: # optional, default is any
        # The Flutter build release channel
        #channel: # optional, default is stable

      - name: Preprocess
        run: |
          rm lib/config/config.dart
          mv lib/config/config.dart.sample lib/config/config.dart
      - name: Prepare
        run: |
          export scripts_path=`pwd`
          export release_bundle_identifier='cn.honjow.fehv'
          export dev_bundle_identifier='dev2.cn.honjow.fehv'
          export pub_output_path="$HOME/Public/fehv";
          export ipa_plist_path="${ios_archiver_path}/Info.plist"
          export apk_build_path="${scripts_path}/../build/app/outputs/apk/release/";
          export apk_build_path_universal="${scripts_path}/../build/app/outputs/apk/releaseUniversal/";
          export version=`perl version.pl`
      - name: Build
        run: |
          echo $apk_build_path
          echo $apk_build_path_universal

          flutter build apk
          cp -R $apk_build_path $apk_build_path_universal
          flutter build apk --split-per-abi
          cp $apk_build_path_universal/*.apk $apk_build_path/*
    # - name: Upload a Build Artifact
    #   uses: actions/upload-artifact@v3.1.0
    #   with:
    #     # Artifact name
    #     name: # optional, default is artifact
    #     # A file, directory or wildcard pattern that describes what to upload
    #     path:
